#!/bin/bash

# Dependencies: xdotool (sudo apt-get install xdotool)

# Functions

# add command so it works with ssh (no gui)
# DISPLAY=:0

save_active () {
    # get current workspace
    ActiveDesktop="$( DISPLAY=:0 xdotool get_desktop)"
    # get current active window ID
    ActiveWindowID="$( DISPLAY=:0 xdotool getactivewindow)"
    # get current active window name
    ActiveWindowName="$( DISPLAY=:0 xdotool getwindowname "$ActiveWindowID")"
}

restore_active(){
    DISPLAY=:0 xdotool set_desktop "$ActiveDesktop"
    # Activating the root window (Desktop) results in an error message, so we
    # try to avoid it
    [[ "$ActiveWindowName" != "Desktop" ]] && DISPLAY=:0 xdotool windowactivate "$ActiveWindowID"
}

youtube_playpause(){
  DISPLAY=:0 xdotool search --name YouTube windowactivate
  sleep 0.1
  DISPLAY=:0 xdotool key --clearmodifiers 'f'
}

# Main

## save active window and desktop
save_active
## activate Chrome YouTube window and send keyboard event
youtube_playpause
## restore previously active window/desktop
restore_active
